apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: 502207623589.dkr.ecr.us-east-1.amazonaws.com/terraform-demo:tagVersion
          ports:
            - containerPort: 3000
